### ISSUE TITLE
Docker Install Instructions

### ISSUE THREAD

**Issue by DevilsDesigns** [iamklaus/nextcloud#3]
could you please post the default nextcloud compose.
Ive tried this below to no avail

```
docker run -d \
  --name=nextcloud \
  --network=proxynet \
  -e PUID=99 \
  -e PGID=100 \
  -e TZ=America/Chicago \
  -p 444:443 \
  -v /mnt/disk1/appdata/nextcloud:/config \
  -v /mnt/disk1/appdata/nextcloud/data:/data \
  --restart unless-stopped \
  iamklaus/nextcloud:fpm
```

**Comment by guystreeter** [comment]
The docker image is based on the official Nextcloud docker image, and its usage is described [here](https://github.com/docker-library/docs/blob/master/nextcloud/README.md).
