### ISSUE TITLE
Unable to start container when "--user" option is beeing used

### ISSUE THREAD

**Issue by rastaralle** [iamklaus/nextcloud#4]
Hey Klaus, 

during my investigations on using the face recognition app inside docker I found your repo and just tested it out.
On my setup I have to run the NC container as a special user (NC data dir readable for others processes as well).
When doing so, I get several permission denied errors with the result of the container not starting. Without the --user option the container starts just fine on my setup.
See here for further details on the --user option: https://github.com/nextcloud/docker/issues/359

[Docker log](https://github.com/iamklaus/nextcloud/files/6290625/nextcloud_face.log)

My settings im compose file:
  nextcloud-face:
    image: iamklaus/nextcloud:latest
    container_name: nextcloud_face
    user: 1000:100   #commenting this out and the container works just fine
    environment:
      - TZ=Europe/Berlin
    volumes:
      - /****/configfiles/nextcloud-face:/var/www/html
    ports:
      - 450:443
      - 451:80
    depends_on:
      - mariadb
    restart: unless-stopped

Greetings 
Ralle

**Comment by rastaralle** [comment]
Executing the below fixed it me (locally):

sudo docker exec -ti nextcloud_face /bin/bash
chmod 777 /var/log/supervisord/supervisord.log

**Comment by iamklaus** [comment]
Can't reproduce this.

**Comment by iamklaus** [comment]
Can't reproduce this.
